Stackoverflow/Models/Questions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StackOverflow.Models
{
    public class Questions
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public string Tag4 { get; set; }
        public string Tag5 { get; set; }
        public string comment { get; set; }
        public string votes { get; set; }
        public string EmpComment { get; set; }
        public string UserReacted { get; set; }
        public DateTime DateTimePosted { get; set; }
        public string EmpCommentDateTimePosted { get; set; }
    }
}

Stackoverflow/Pages/AskaQuestion.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StackOverflow.Models;

namespace StackOverflow.Pages.HomePage
{
    public class AskaQuestionModel : PageModel
    {
        public int edit { get; set; }
        public int id { get; set; }
        public Questions questions { get; set; }
        public void OnGet(int edit,int id)
        {
            if (edit == 1)
            {
                this.edit = edit;
                this.id = id;
                //questions = Utilities.Util.GetQuestion(id);
            }
        }
        
        public IActionResult OnPostSubmit()
        {
            string Title = Request.Form["title"] ;
            string Description = Request.Form["editor"];
            string Tags = Request.Form["tags"];
            string communication = Request.Form["isChecked"]=="on"?"1":"0";
            Description = Description.Replace("'","''");
            if (Utilities.Util.InsertQuestion( Title, Description, Tags, communication))
            {
                return Redirect("~/Index");
            }
            return Redirect("~/Error");
        }
        
    }
}

Stackoverflow/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StackOverflow.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Stackoverflow/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using StackOverflow.Models;
using StackOverflow.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace StackOverflow.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public  List<Questions> questions = new List<Questions>();
        public static IHttpContextAccessor ac;
        public string name;

        public IndexModel(ILogger<IndexModel> logger,IHttpContextAccessor contextAccessor)
        {
            _logger = logger;
            ac = contextAccessor;
        }

        public void OnGet(string profile)
        {
            name = "bphanipranav";//ac.HttpContext.User.FindFirst(ClaimTypes.Name).Value.Replace("WINNTDOM\\","");
            var x = Util.UserDetail(name);
            Util u = new Util(ac);
            name = Util.GetUserName();
            if (profile == "1")
                questions = Util.GetQuestions("1",name);
            else
                questions = Util.GetQuestions("",name);

        }
        public static string GetUser()
        {
            return ac.HttpContext.User.FindFirst(ClaimTypes.Name).Value;
        }
    }
}

Stackoverflow/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StackOverflow.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Stackoverflow/Pages/Question.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json.Linq;

using StackOverflow.Models;

namespace StackOverflow.Pages
{
    public class QuestionModel : PageModel
    {
        public List<Questions> q = new List<Questions>();
        public List<Answers> ans = new List<Answers>();
        public int id;
        public bool isThereAnswer = false;
        public void OnGet(int id)
        {
            this.id = id;
           q =  Utilities.Util.GetQuestion(id);
           ParseAnswerData(Utilities.Util.GetAnswers(id));
        }
        public IActionResult OnPostSubmit()
        {
            var PostId = Request.Form["id"];
            var edito = Request.Form["editor"].ToString().Replace("'","''");
            if (Utilities.Util.InserUserAnswer(PostId, edito))
            {
                return Redirect("~/Index");
            }
            return Redirect("~/Error");
        }
        public IActionResult OnPostAnswerThis()
        {
            if(Utilities.Util.InserSubmittedAnswer(Request.Form["Answerid"].ToString()))
                return Redirect("~/Index");
            return Redirect("~/Error");
        }
        public ActionResult OnGetSubmitReaction(string reaction, string post, string answer, string isanswer)
        {
            return new JsonResult( Utilities.Util.InsertReaction(reaction, post, answer, isanswer).ToString() );
        }
        public IActionResult OnPostAddComment()
        {
            var AnswerID = Request.Form["Answerid"];
            var PostID = Request.Form["PostID"];
            var edito = Request.Form["comment"];
            var id = Request.Form["PostIDfor"];
            id = string.IsNullOrEmpty(PostID) ?id:PostID;
           
            if (Utilities.Util.InserUserComment(PostID,AnswerID, edito))
            {
                return Redirect($"~/Question?id={id}");
            }
            return Redirect("~/Error");
        }
        public void ParseAnswerData(string s)
        {
            string json = s;
            if (s == "")
            {

            }
            else
            {
                var getResult = JArray.Parse(json);             
                foreach (JObject o in getResult.Children<JObject>())
                {

                    Answers a = new Answers();
                    a.IsAnswer = o["IsAnswer"].ToString();
                    if(a.IsAnswer == "True")
                    {
                        isThereAnswer = true;
                    }
                    a.Title = o["Title"].ToString();
                    a.AnswerID = o["AnswerID"].ToString();
                    a.AnswerDescription = Utilities.Util.GetAnswerDewscription(a.AnswerID);

                    a.PostID = o["PostID"].ToString();
                    a.EmployeeName = o["EmployeeName"].ToString();
                    a.DatePosted = o["DateTimePosted"].ToString();
                    a.PostID = o["PostID"].ToString();
                    a.votes = o["Votes"].ToString();
                    a.IsUserReacted = o["userreacted"].ToString();
                    var x = (JArray)o["C"];
                    if (x.HasValues)
                    {
                        List<Comments> comm = new List<Comments>();
                        foreach (JObject o1 in x.Children<JObject>())
                        {
                            if (o1.Count > 0)
                            {
                                Comments c = new Comments();
                                c.commentID = o1["CommentID"].ToString();
                                c.EmployeeName = o1["EmployeeName"].ToString();
                                c.PostID = o1["PostID"].ToString();
                                c.AnswerID = o1["AnswerID"].ToString();
                                c.Comment = o1["Comment"].ToString();
                                c.DateTimePOsted = o1["DateTimePosted"].ToString();
                                comm.Add(c);
                            }
                        }
                        a.comments = comm;
                    }
                    ans.Add(a);
                }
            }
        }

    }
}

Stackoverflow/Pages/SearchOutput.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
//using SearchEngine;
using StackOverflow.Models;

namespace StackOverflow.Pages.HomePage
{

    public class SearchOutputModel : PageModel
    {
        public List<Questions> questions = new List<Questions>();
        public string searchText { get; set; }
        public void OnGet(string search)
        {
            searchText = search;
            //List<SearchResult>  result =  SearchEngine.Program.Main(search);
            //string query = "";
            //foreach(var x in result)
            //{
            //    query += x.id.ToString()+",";
            //}
            //if (query.Length > 2)
            //{
            //    query = query.Substring(0, query.Length - 1);
            //    questions = Utilities.Util.GetSearchQuestions(query);
            //}
        }
    }
}

Stackoverflow/Pages/UserRegistration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StackOverflow.Pages
{
    public class UserRegistrationModel : PageModel
    {
        public int RegistrationSuccess = 0;
        public void OnGet()
        {
            RegistrationSuccess = Utilities.Util.IsUserRegistered;
        }
        public IActionResult OnPostSubmit()
        {
            var deartment = Request.Form["Department"];
            var team = Request.Form["Team"];
            var alert = Request.Form["isChecked"];
            var tags = Request.Form["Tags"];
            if (Utilities.Util.InserUserDetails(deartment, team, tags, alert))
            {
                RegistrationSuccess = 1;
                string user = Utilities.Util.GetUserName();
                Utilities.SendMail.MailUser($"Hi {user}.\r\rWelcome to AKIO. The single destination for your questions in Micron.\r",user+"@micron.com","","Registration Success");
                return Redirect("~/Index");
            }
            else
            {
                return Redirect("~/Error");
            }
        }
    }
}

Stackoverflow/Pages/AskaQuestion.cshtml
@page
@model StackOverflow.Pages.HomePage.AskaQuestionModel
@{
}
<h3>Ask a Public Question that is internal to Micron Technologies.</h3>
<br />
@if (Model.edit == 1)
{
    <div>
        <form method="post">
            <div id="AskEdit" style="background-color:white;">
                Title<br />
                <input class="form-control" name="title" id="title" type="text" value="@Model.questions.Title"  required />
                <br />
                <br />
                Body(Description)<br />
                <textarea id="editor" name="editor"></textarea>
                <br />
                Tags<br />
                <input class="form-control" name="tags" id="tags" type="text" value="@Model.questions.Tag1,@Model.questions.Tag2,@Model.questions.Tag3,@Model.questions.Tag4,@Model.questions.Tag5" placeholder="Please add tags in comma separated values" data-role="tagsinput" />
                <br />
                <br />
                We will send mail to people for registered members
                <input class="form-control" type="checkbox" name="isChecked" id="check" checked data-toggle="toggle" data-size="xs">
            </div>
            <div>
                <br />
                <button asp-page-handler="Submit" class="btn-info" id="SubmitQuestion">Submit Question</button>
            </div>
        </form>
    </div>

}
else
{
    <div>
        <form method="post">
            <div id="Ask" style="background-color:white;">
                Title<br />
                <input class="form-control" name="title" id="title" type="text" required />
                <br />
                <br />
                Body(Description)<br />
                <textarea id="editor" name="editor"></textarea>
                <br />
                Tags<br />
                <input class="form-control" name="tags" id="tags" type="text" placeholder="Please add tags in comma separated values" data-role="tagsinput" />
                <br />
                <br />
                We will send mail to people for registered members
                <input class="form-control" type="checkbox" name="isChecked" id="check" checked data-toggle="toggle" data-size="xs">
            </div>
            <div>
                <br />
                <button asp-page-handler="Submit" class="btn-info" id="SubmitQuestion">Submit Question</button>
            </div>
        </form>
    </div>
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    function getData() {
        var myContent = tinymce.get("editor").getContent();
        var X = @Model.edit;
        console.log(x);
        console.log(myContent);
    }
    $('#SubmitQuestion').on('click', function () {
        var Description = tinymce.get("editor").getContent();

        var title = $('#title').val();
        var Tags = $('#tags').val();
        var communication = $('#check').val();
        var X = @Model.edit;
        console.log(x);
        $.ajax({
            url: "/?handler=Index",
            data: { Title: title, Description: Description, Tags: Tags, communication: communication },
            success: function (data) {
                console.log(1)
            },
            error: function () {

            }
        });
    })
</script>

Stackoverflow/Pages/Index.cshtml
@page
@model StackOverflow.Pages.IndexModel

<h3 style="padding:12px;">Top Questions</h3>
<hr style="border-block-width:7px;color:black" />
@for (int i = 0; i < Model.questions.Count; i++)
{
    <div class="card" style="width: inherit">
        <div class="card-body">
            <a href="~/Question?id=@Model.questions[i].ID"> @Model.questions[i].Title</a>
            <a style="float:right;font-size:12px;background-color:transparent;color:cornflowerblue;border:none;outline:none;"class="btn btn-primary" data-toggle="collapse" href="#Q_@i" role="button" aria-expanded="false" aria-controls="Q_@i">
                Show complete question
            </a>
            <div class="collapse" id="Q_@i">
                &emsp;
                @Html.Raw(Model.questions[i].Description)
            </div>
            <br />
            <div class="row">
                <p class="QuestionTag"> @Model.questions[i].Tag1</p>&nbsp;
                @if (Model.questions[i].Tag2 != "")
                {
                    <p class="QuestionTag"> @Model.questions[i].Tag2</p>
                }
                &nbsp;
                @if (Model.questions[i].Tag3 != "")
                {
                    <p class="QuestionTag"> @Model.questions[i].Tag3</p>
                }
                &nbsp;
                @if (Model.questions[i].Tag4 != "")
                {
                    <p class="QuestionTag"> @Model.questions[i].Tag4</p>
                }
                &nbsp;
                @if (Model.questions[i].Tag5 != "")
                {
                    <p class="QuestionTag"> @Model.questions[i].Tag5</p>
                }

            </div>
            @*@Html.Raw(Model.questions[i].Description)*@
        </div>
        <div class="card-footer" style="padding-top:7px;font-size:12px;">
            <button class="like bi bi-hand-thumbs-up-fill" style="background-color: transparent; border: transparent; outline: none; font-size: 21px;" disabled>
            </button>23&nbsp;
            <button class="dislike bi bi-hand-thumbs-down-fill" style="background-color: transparent; border: transparent; outline: none; font-size: 21px;" disabled>
            </button>12&nbsp;
            <p style="float:right;padding-top:4px;">by&nbsp;@Model.questions[i].EmployeeName</p>&nbsp;
            <p style="float:right;padding-top:4px;">
                @Model.questions[i].DateTimePosted
            </p>&nbsp;
        </div>

    </div>
    <hr style="border-block-width:3px" />

}
<link href="~/css/site.css" rel="stylesheet" />

Stackoverflow/Pages/Question.cshtml
@page
@model StackOverflow.Pages.QuestionModel
@{
}
<h1 class="card-title">@Model.q[0].Title</h1>
<br />
<h4>@Model.q[0].EmployeeName</h4>
<div class="card" id="QuestionUserDiv" style="width: 70rem; position: sticky; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">
    <div class="card-title">
    </div>
    <div class="card-body">
        @Html.Raw(Model.q[0].Description)
        &emsp;<div class="row">
    @if (Model.q[0].Tag1 != "")
    {
        <p class="QuestionTag"> @Model.q[0].Tag1</p>
    }
    &nbsp;
    @if (Model.q[0].Tag2 != "")
    {
        <p class="QuestionTag"> @Model.q[0].Tag2</p>
    }
    &nbsp;
    @if (Model.q[0].Tag3 != "")
    {
        <p class="QuestionTag"> @Model.q[0].Tag3</p>
    }
    &nbsp;
    @if (Model.q[0].Tag4 != "")
    {
        <p class="QuestionTag"> @Model.q[0].Tag4</p>
    }
    &nbsp;
    @if (Model.q[0].Tag5 != "")
    {
        <p class="QuestionTag"> @Model.q[0].Tag5</p>
    }

</div>

    </div>
    <hr />

    <div>
        @for (int i = 0; i < Model.q.Count; i++)
        {
            <h6 style="font-size: 12px; float: right; padding-top: 5px; margin-right: 2px;"> @Model.q[i].comment <br />- &nbsp;<span style="color:aqua">@Model.q[i].EmpComment</span> &nbsp; on &nbsp; @Model.q[i].EmpCommentDateTimePosted </h6>
            <hr style="width:90%;float:right" />
        }
        <form method="post">
            <div class="row">
                <input type="text" name="PostID" value="@Model.q[0].ID" hidden />
                <input type="text" name="comment" placeholder="Add Comment..." class="form-control" style="border:none;" required/>
                <button asp-page-handler="AddComment">Add comment</button>
            </div>
        </form>
    </div>
    <div class="card-footer">
        <div style="float:left; display:flex">
            <button class="bi bi-hand-thumbs-up-fill" value="@Model.q[0].ID" style="background-color: transparent; border: transparent; outline: none; font-size: 21px;  color:@Util.Like(Model.q[0].UserReacted)" id="Like" @Util.LikeDisabled(Model.q[0].UserReacted)>
            </button>
            <h5 id="vot_@Model.q[0].ID">
                @Model.q[0].votes
            </h5>
            <button class="bi bi-hand-thumbs-down-fill" value="@Model.q[0].ID" style="background-color: transparent; color: @Util.Dislike(Model.q[0].UserReacted); border: transparent; outline: none; font-size: 21px;" id="DisLike" @Util.LikeDisabled(Model.q[0].UserReacted)>
            </button>
        </div>
        <button style="float:right;" class="btn-primary" onclick="ScrollToAnswer()">Know the Answer?</button>
    </div>
</div>
<br />
<h2><b>Answers</b></h2>
@for (int i = 0; i < Model.ans.Count; i++)
{
<div class="card" style="width: 70rem; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">


    <div class="card-header " style="margin-left:0px;margin-right:0px;align-items:center">
        @if (Model.ans[i].IsAnswer == "True")
        {
            <button class="form-control btn btn-success" disabled>Answered</button>
        }
        @if (Model.isThereAnswer == false && Model.q[0].EmployeeName.ToUpper() == Util.GetUserName().ToUpper() )
        {
            <form method="post">
                <input type="text" id="AnswerIdforLike_@i" name="AnswerID" value="@Model.ans[i].AnswerID" hidden />
                <button asp-page-handler="AnswerThis" class="form-control btn btn-outline-success">Mark this as Answer?</button>
            </form>
        }
        <div style="float:left; display:flex">
            <input type="text" id="AnswerIdforLike_@i" name="AnswerID" value="@Model.ans[i].AnswerID" hidden />
            <button class="like bi bi-hand-thumbs-up-fill" value="@i" style="background-color: transparent; border: transparent; outline: none; font-size: 21px;  color:@Util.Like(Model.ans[i].IsUserReacted)" id="Like_@i" )>
            </button>
            <h5 id="vot_@i"> @Model.ans[i].votes</h5>
            <button class="dislike bi bi-hand-thumbs-down-fill" value="@i" style="background-color: transparent; color: @Util.Dislike(Model.ans[i].IsUserReacted); border: transparent; outline: none; font-size: 21px;" id="DisLike_@i" )>
            </button>
        </div>
        <div>
            <em style="float:right">Posted by @Model.ans[i].EmployeeName on @Model.ans[i].DatePosted</em>
        </div>



    </div>
    <div class="card-body" id="A_@i">
        @Html.Raw(Model.ans[i].AnswerDescription)
    </div>
    <div>
        <a style="float:right;font-size:12px;background-color:transparent;color:cornflowerblue;border:none;outline:none;" class="btn btn-primary" data-toggle="collapse" href="#C_@i" role="button" aria-expanded="false" aria-controls="C_@i">
            Show Comments
        </a>
    </div>
    <div id="C_@i" class="collapse">
    <hr />
    <span style="
    font-weight: 600;
    font-size: 21px;
">Comments</span>
        @for (int j = 0; j < Model.ans[i].comments.Count; j++)
        {
            <div style="padding-left: 10%; padding-right: 2px; ">
                <div style="background-color: #e3e0e0; border-radius: 8px; padding-bottom: 4px">

                    <h6 style="padding-left:11px; padding-top:8px">@Model.ans[i].comments[j].Comment</h6>
                    <h6 style="float:right;padding-top:6px;">-by @Model.ans[i].comments[j].EmployeeName on @Model.ans[i].comments[j].DateTimePOsted</h6>
                </div>
            </div>
            <br />
        }
    <form method="post">
        <div class="row" style="margin-right: 0px; margin-left: 0px;">
            <input type="text" name="PostIDfor" value="@Model.q[0].ID" hidden />
            <input type="text" name="AnswerID" value="@Model.ans[i].AnswerID" hidden />
            
            <input type="text" name="comment" placeholder="Add Comment..." class="form-control" style="border:none;" required />
            <button style="float:right" asp-page-handler="AddComment">Add comment</button>
        </div>
    </form>
    </div>
</div>
   <br />
}
@ViewData["Yes"]
<div class="userAnswer" id="UserAnswerDiv">
    <form method="post">

        <h2><b>Your Answer</b></h2>

        Body(Description)<br />
        <input type="text" name="id" value="@Model.q[0].ID" hidden />
        <textarea id="editor" name="editor"></textarea>

        <br />
        <button class="btn-primary" onclick="ScrollToQuestion()">Want to see question?</button>&nbsp;&nbsp;
        <button style="float:right" asp-page-handler="Submit" class="btn-success">Post Answer</button>
    </form>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script>
    function ScrollToAnswer() {
        const element = document.getElementById("UserAnswerDiv");
        element.scrollIntoView();
    }
    function ScrollToQuestion() {
        const element = document.getElementById("QuestionUserDiv");
        element.scrollIntoView();
    }
    $(".like").click(function () {
        this.pre
        var fired_button = $(this).val();
        $(this).css('color', '#59b559');
        var dislike = document.getElementById("DisLike_" + fired_button);
        var Vot = document.getElementById("vot_" + fired_button).innerHTML;
        var AnswerId = document.getElementById("AnswerIdforLike_" + fired_button).value;
        
        dislike.style.color = 'gray';
        $.ajax({
            dataType: 'json',
            contentType:'application/json',
            url: "Question/?handler=SubmitReaction",
            data: { reaction: '1', post: '0', answer: AnswerId,isanswer:1 },
            success: function (data) {
                document.getElementById("Like_" + fired_button).disabled = true;
                document.getElementById("DisLike_" + fired_button).disabled = false;
                document.getElementById("vot_" + fired_button).innerHTML = data;
                console.log(data)
            },
            error: function () {

            }
        });
    });
    $(".dislike").click(function () {
        var fired_button = $(this).val();
        $(this).css('color', '#ff5b5b');
        var dislike = document.getElementById("Like_" + fired_button);
        var Vot = document.getElementById("vot_" + fired_button).innerHTML;
       
        var AnswerId = document.getElementById("AnswerIdforLike_" + fired_button).value;
        dislike.style.color = 'gray';
        $.ajax({
            dataType: 'json',
            contentType: 'application/json',
            url: "Question/?handler=SubmitReaction",
            data: { reaction: '-1', post: '0', answer: AnswerId, isanswer: 1 },
            success: function (data) {
                document.getElementById("Like_" + fired_button).disabled = false;
                document.getElementById("DisLike_" + fired_button).disabled = true;
                document.getElementById("vot_" + fired_button).innerHTML = data;
                console.log(data)

            },
            error: function () {

            }
        });
    });
    $("#Like").click(function () {
        this.pre
        var fired_button = $(this).val();
        $(this).css('color', '#59b559');
        var dislike = document.getElementById("DisLike");
        var Vot = document.getElementById("vot_" + fired_button).innerHTML;
        
        dislike.style.color = 'gray';
        $.ajax({
            dataType: 'json',
            contentType:'application/json',
            url: "Question/?handler=SubmitReaction",
            data: { reaction: '1', post: fired_button, answer: '0', isanswer: 0 },
            success: function (data) {
                document.getElementById("Like").disabled = true;
                document.getElementById("DisLike").disabled = false;
                document.getElementById("vot_" + fired_button).innerHTML = data;
            },
            error: function () {

            }
        });
    });
    $("#DisLike").click(function () {
        var fired_button = $(this).val();
        $(this).css('color', '#ff5b5b');
        var dislike = document.getElementById("Like");
        var Vot = document.getElementById("vot_" + fired_button).innerHTML;
        
        dislike.style.color = 'gray';
        $.ajax({
            dataType: 'json',
            contentType: 'application/json',
            url: "Question/?handler=SubmitReaction",
            data: { reaction: '-1', post: fired_button, answer: '0', isanswer: 0 },
            success: function (data) {
                document.getElementById("Like").disabled = false;
                document.getElementById("DisLike").disabled = true;
                document.getElementById("vot_" + fired_button).innerHTML = data;
            },
            error: function () {

            }
        });
    });
</script>

Stackoverflow/Pages/UserRegistration.cshtml
@page
@model StackOverflow.Pages.UserRegistrationModel
@{
}
@if (Model.RegistrationSuccess == 0 )
{
    <div class="border-success">
        <form method="post">
            
            <label>Your Department</label>&nbsp;&nbsp;<input class="form-control" name="Department" value="" required/><br />
            <label>Your Team Name</label>&nbsp;&nbsp;<input class="form-control" name="Team" value="" required/><br />
            <label>Are you willing to receive alerts</label>&nbsp;&nbsp;<input class="form-control" type="checkbox" name="isChecked" id="check" checked data-toggle="toggle" value="1" data-size="xs"><br />
            <label>Tags of your Technology Expertise</label>&nbsp;&nbsp;<input class="form-control" value="" name="Tags" placeholder="Enter comma separated tags" required/><br />
            <button asp-page-handler="Submit" class="btn-outline-info">Submit</button>
        </form>
    </div>
}
else
{
<p>You have registered successfully</p>
}